### ISSUE TITLE
KeyError: 'bitcoin'

### ISSUE THREAD

**Issue by danmir** [Neisklar/p2pool-quarkcoin#2]
Hello. I have this problem on my Ubuntu. Bitcoind and Quarkcoind are running. I try to do: python run_p2pool.py
Traceback (most recent call last):
  File "run_p2pool.py", line 5, in <module>
    main.run()
  File "/root/p2pool-quarkcoin-master/p2pool/main.py", line 455, in run
    net = networks.nets[net_name]
KeyError: 'bitcoin'

**Comment by gclsoft** [comment]
I've the same problem,how did you solve  it?

**Comment by danmir** [comment]
You have to start it with specific keys
